apiVersion: backstage.io/v1alpha1
kind: Resource
metadata: 
  name: "vnet-bobit847hju-prod-us-east-001"
  annotations:
    github.com/project-slug: ibrt2016/terraform-azure-infra-bobit847hju # Change the value to your github repo which contains terraform code.
    backstage.io/techdocs-ref: dir:.
  links:
  - url: https://github.com/ibrt2016/terraform-azure-infra-bobit847hju/blob/8890-prod-createvnet/8890-vnet.tf
    title: 'Virtual Network Terraform Instance'
    icon: github
  tags:
    - azure
    - vnet
    - terraform
    - high-criticality
    - ticket-number-8890
    - entity-uk
    - owner-bob-tayara
    - stack-bobit847hju
    - env-prod
    - created-on-2024-07-30
  description: |
   **Azure Virtual Network** in stack **bobit847hju** and in **prod** environment\
   \
   **Ticket number:**  8890\
   **Created on:**  2024-07-30\
   **Details:**  Create an **Azure Virtual network** in stack **bobit847hju**, in **prod** environment, in **us-east** region with suffix **001**\
   **Action:**  Create a new Virtual Network **vnet-bobit847hju-prod-us-east-001**\
   **Azure region:**  us-east\
   **Virtual network address space:**  10.31.0.0/16\
   **Virtual network suffix:**  001\
   **Stack name:**  bobit847hju\
   **Stack owner:**  bob-tayara\
   **Azure subscription:**  infra\
   **Criticality:**  High\
   **Entity:**  UK\
   **Cost center:**  00055
spec:
  type: azure-virtual-network
  owner: central-it
  system: bobit847hju-terraform-azure-infra